In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text' : ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output' : [1,1,0,0]})

In [3]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
# printing the vocabulary (unique words present in the corpus)

print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [11]:
print(bow[0].toarray())    # 1st sentence
print(bow[1].toarray())    # 2nd sentence

# so we can see our output as a vector below

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [12]:
# take a new sentence and predict for it :-

cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])